requires 'IPC::System::Simple',    '1.21';
requires 'App::Cmd',               '0.323';
requires 'IO::Uncompress::Gunzip';
requires 'IO::Uncompress::Bunzip2';
requires 'IO::Compress::Gzip';
requires 'IO::Compress::Bzip2';
requires 'File::Copy';
requires 'Capture::Tiny';
requires 'HTTP::Tiny';
requires 'XML::LibXML';
requires 'HTML::TableExtract';
requires 'Net::FTP';
