requires 'LWP::UserAgent',         '6.05';
requires 'IPC::System::Simple',    '1.21';
requires 'App::Cmd',               '0.323';
requires 'IO::Uncompress::Gunzip';
requires 'File::Copy';
requires 'Capture::Tiny';
requires 'XML::LibXML';
requires 'HTML::TableExtract';
requires 'File::Find::Rule';
requires 'Try::Tiny';
