name: CI
on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        perl: [ '5.34', '5.32', '5.30' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: sudo apt-get install emboss hmmer libdb-dev zlib1g-dev libxml2-dev libexpat1-dev libssl-dev
      - run: perl -V
      - run: echo "n" | cpanm -n  Data::Stag DB_File Bio::Root::Version Bio::DB::Taxonomy::entrez
      - run: cpanm --installdeps .
      - run: perl Makefile.PL && make
      - run: prove -lv t
